### PR TITLE
allow kahlan dev-4.0 usage

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by jails** [comment]
I don't this one is necessary

**Comment by samsonasik** [comment]
if I want to try kahlan `dev-4.0`, without this, I will get error: 
```
Problem 1
    - The requested package kahlan/kahlan dev-4.0 exists as kahlan/kahlan[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.1.7, 1.1.8, 1.1.9, 1.2.0, 1.2.1, 1.2.10, 1.2.11, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 1.2.7, 1.2.8, 1.2.9, 1.3.0, 1.3.1, 1.3.2, 1.3.x-dev, 2.0.0, 2.0.1, 2.1.0, 2.2.0, 2.3.0, 2.3.1, 2.3.2, 2.4.0, 2.4.1, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.5.4, 2.5.5, 2.5.6, 2.5.7, 2.5.8, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.1.0, 3.1.1, 3.1.10, 3.1.11, 3.1.12, 3.1.13, 3.1.14, 3.1.15, 3.1.16, 3.1.17, 3.1.2, 3.1.3, 3.1.4, 3.1.5, 3.1.6, 3.1.7, 3.1.8, 3.1.9, 4.0.x-dev, dev-4.0-phony, dev-dev, dev-master] but these are rejected by your constraint.
```

**Comment by samsonasik** [comment]
or probably something I missed.

**Comment by jails** [comment]
Oh ok, but do you think we should be able to leave `"php": ">=5.4"` for now for this package ?

**Comment by samsonasik** [comment]
I think I got the culprit, I was set:
```
        "kahlan/kahlan": "dev-4.0",
```
which should be:
```
        "kahlan/kahlan": "4.0.x-dev",
```

**Comment by samsonasik** [comment]
travis green which use `kahlan:4.0.x-dev` at php 5.5+ https://travis-ci.org/kahlan/extra-matcher/builds/263797859?utm_source=github_status&utm_medium=notification

**Comment by jails** [comment]
:+1:

**Pull request merged**
